### ISSUE TITLE
Doesn't work on appcenter

### ISSUE THREAD

**Issue by aksonov** [patniko/detox-appcenter#20]
```
##[section]Initializing Hosted Agent
....
CompileC /Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Intermediates.noindex/RCTText.build/Release-iphonesimulator/RCTText.build/Objects-normal/i386/RCTTextField.o RCTTextField.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vsts/agent/2.133.3/work/1/s/node_modules/react-native/Libraries/Text
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_9.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode_9.3.1.app/Contents/Developer/usr/bin:/usr/local/opt/nvm/versions/node/v8.5.0/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy:./simutils/build/Build/Products/Release"
    /Applications/Xcode_9.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/vsts/agent/2.133.3/work/1/s/ios/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/agent/2.133.3/work/1/s/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-para...

CompileC /Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Intermediates.noindex/RCTText.build/Release-iphonesimulator/RCTText.build/Objects-normal/i386/RCTText.o RCTText.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vsts/agent/2.133.3/work/1/s/node_modules/react-native/Libraries/Text
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_9.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode_9.3.1.app/Contents/Developer/usr/bin:/usr/local/opt/nvm/versions/node/v8.5.0/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy:./simutils/build/Build/Products/Release"
    /Applications/Xcode_9.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/vsts/agent/2.133.3/work/1/s/ios/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/agent/2.133.3/work/1/s/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-para...

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Intermediates.noindex/RCTText.build/Release-iphonesimulator/RCTText.build/Objects-normal/i386/RCTTextView.o RCTTextView.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
child_process.js:634
    throw err;
    ^

Error: Command failed: xcodebuild -project ios/example.xcodeproj -scheme example -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/Users/vsts/agent/2.133.3/work/1/s/node_modules/detox/local-cli/detox-build.js:26:6)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
Executing tests...
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release  --cleanup    


detox-server info 08:20:31: server listening on localhost:54098...
  1) "before all" hook

  0 passing (100ms)
  1 failing

  1) "before all" hook:
     Error: app binary not found at '/Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Products/Release-iphonesimulator/example.app', did you build it?
      at Device._getAbsolutePath (node_modules/detox/src/devices/Device.js:206:13)
      at Device.prepare (node_modules/detox/src/devices/Device.js:19:29)
      at Detox.init (node_modules/detox/src/Detox.js:72:23)
      at <anonymous>



detox info 1: Shutting down undefined... 
  2) "after all" hook

  0 passing (1s)
  2 failing

  1) "before all" hook:
     Error: app binary not found at '/Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Products/Release-iphonesimulator/example.app', did you build it?
      at Device._getAbsolutePath (node_modules/detox/src/devices/Device.js:206:13)
      at Device.prepare (node_modules/detox/src/devices/Device.js:19:29)
      at Detox.init (node_modules/detox/src/Detox.js:72:23)
      at <anonymous>

  2) "after all" hook:
     Error: Command failed: /usr/bin/xcrun simctl shutdown undefined
Invalid device: undefined
 `/usr/bin/xcrun simctl shutdown undefined` (exited with error code 163)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)




  0 passing (1s)
  2 failing

  1) "before all" hook:
     Error: app binary not found at '/Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Products/Release-iphonesimulator/example.app', did you build it?
      at Device._getAbsolutePath (node_modules/detox/src/devices/Device.js:206:13)
      at Device.prepare (node_modules/detox/src/devices/Device.js:19:29)
      at Detox.init (node_modules/detox/src/Detox.js:72:23)
      at <anonymous>

  2) "after all" hook:
     Error: Command failed: /usr/bin/xcrun simctl shutdown undefined
Invalid device: undefined
 `/usr/bin/xcrun simctl shutdown undefined` (exited with error code 163)
      at callback (node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:277:5)
      at maybeClose (internal/child_process.js:927:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)



child_process.js:634
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release  --cleanup    
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at runMocha (/Users/vsts/agent/2.133.3/work/1/s/node_modules/detox/local-cli/detox-test.js:61:6)
    at Object.<anonymous> (/Users/vsts/agent/2.133.3/work/1/s/node_modules/detox/local-cli/detox-test.js:39:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
##[error]/bin/bash failed with return code: 1
##[error]Bash failed with error: /bin/bash failed with return code: 1
##[section]Finishing: Post Clone Script
##[section]Starting: Post Job Cleanup
Cleaning any cached credential from repository: detox-appcenter (Git)
##[command]git remote set-url origin https://github.com/aksonov/detox-appcenter.git
##[command]git remote set-url --push origin https://github.com/aksonov/detox-appcenter.git
##[section]Finishing: Post Job Cleanup
##[section]Starting: Xcode build (not signed)
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 4.130.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
==============================================================================
##[section]Finishing: Xcode build (not signed)
##[section]Finishing: Job
```

**Comment by sebastianmalcolm** [comment]
@aksonov: If you see the error `app binary not found at '/Users/vsts/agent/2.133.3/work/1/s/ios/build/Build/Products/Release-iphonesimulator/example.app', did you build it?`, then try moving in your `package.json` the Detox configuration `"ios.sim.release"` to be the first configuration.

@patniko: I recommend this issue can be closed because as at Jan 2018, this example project can be built successfully in App Center using Xcode 9.4.1 and Node 8.14 (as installed by `brew install node@8`.
