### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by auwarranties** [patniko/detox-appcenter#34]
*This test should be finished in 40s*
But got timeout error

```warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'react-native-splash-screen' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'react-native-version-number' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'react-native-viewpager' from project 'Pods')
** BUILD SUCCEEDED **

Executing Detox tests...
detox[20504] INFO:  [test.js] configuration="ios" cleanup=true reportSpecs=true useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1594007608459 node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:android:).)*$' --maxWorkers 1 e2e
detox[20505] INFO:  [DetoxServer.js] server listening on localhost:51989...
detox[20505] INFO:  [AppleSimUtils.js] com.directmoneyfinance.Wisr launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 3CF3A2D6-9809-4E83-B8CD-042F75321AC0 log stream --level debug --style compact --predicate 'process == "wisr"'
detox[20505] INFO:  Example is assigned to 3CF3A2D6-9809-4E83-B8CD-042F75321AC0 {"type":"iPhone 11"}
detox[20505] INFO:  Example: register flow
detox[20505] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) reactNativeReload: {}

That might be the reason why the test "Example register flow" has timed out.

detox[20505] INFO:  Example: register flow [FAIL]
detox[20505] INFO:  Example: login flow
detox[20505] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) reactNativeReload: {}

That might be the reason why the test "Example login flow" has timed out.

detox[20505] INFO:  Example: login flow [FAIL]

FAIL e2e/firstTest.e2e.js (312.008s)
  Example
    ✕ register flow (120060ms)
    ✕ login flow (120006ms)

  ● Example › register flow

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | describe('Example', () => {
    > 2 |   beforeEach(async () => {
        |   ^
      3 |     await device.reloadReactNative();
      4 |   });
      5 | 

      at firstTest.e2e.js:2:3
      at Object.<anonymous> (firstTest.e2e.js:1:1)

  ● Example › login flow

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | describe('Example', () => {
    > 2 |   beforeEach(async () => {
        |   ^
      3 |     await device.reloadReactNative();
      4 |   });
      5 | 

      at firstTest.e2e.js:2:3
      at Object.<anonymous> (firstTest.e2e.js:1:1)

detox[20504] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:android:).)*$' --maxWorkers 1 e2e```

**Comment by janaka120** [comment]
@auwarranties Did you resolve this issue?

**Comment by maxckelly** [comment]
Facing the same issue. Anyone have any luck?

**Comment by gillicarmon** [comment]
same here.. works great locally but stuck on beforeAll on appcenter pre build script

**Comment by asaltari** [comment]
I've the same issue. Anyone has solved this?
